### ISSUE TITLE
go 1.5编译问题

### ISSUE THREAD

**Issue by sunyuantao** [blackbeans/kiteq#10]
在go1.5版本下编译会有如下错误：
https://github.com/blackbeans/log4go
package github.com/blackbeans/log4go: unable to parse output of git config remote.origin.url
https://github.com/blackbeans/go-zookeeper
package github.com/blackbeans/go-zookeeper/zk: unable to parse output of git config remote.origin.url
https://github.com/blackbeans/turbo
package github.com/blackbeans/turbo: unable to parse output of git config remote.origin.url

go1.4版本编译正常。

**Comment by blackbeans** [comment]
看一下这个issue https://github.com/golang/go/issues/11713
