### ISSUE TITLE
基于 mysql 存储情况下，消息重复发送

### ISSUE THREAD

**Issue by quguangjie** [blackbeans/kiteq#11]
kiteq启动参数
./kiteq -bind=172.16.1.94:13800 -pport=13801 -db="mysql://172.16.1.94:3306,172.16.1.94:3306?=kite&username=root&password=123456&maxConn=50&batchUpdateSize=1000&batchDelSize=1000&flushPeriod=1000" -topics=order_status,feed -zkhost=localhost:2181 

启动消费者
启动生产者，生产者只发送一条消息后，
消费者消费该消息后，并正确回应服务器，但是还重复接收到这条消息。

之后， kiteq 启动参数 flushPeriod=1000  改为 flushPeriod=1  暂时没有该现象了！

**Comment by blackbeans** [comment]
增加对投递事件的注册避免短时间内因为异步删除更新投递结果时间差导致重复消息
