### ISSUE TITLE
KiteQClient客户端要怎样启动？

### ISSUE THREAD

**Issue by setdi** [blackbeans/kiteq#12]
请问一下，KiteQClient客户端要怎样启动？

**Comment by blackbeans** [comment]
在Readme.md中有说明，当前还没有将client端独立抽离出来可以直接依赖的包，后面会和KiteqServer独立开成为单独的依赖包

**Comment by blackbeans** [comment]
已经将工程拆分可以独立依赖kiteq-client-go进行应用开发了。kiteq单独部署，详见我kiteq-client-go
