### ISSUE TITLE
zookeeper监听执行了两次

### ISSUE THREAD

**Issue by ygqwan** [blackbeans/kiteq#13]
blackbeans你好，
func (self *ZKManager) Start() 这个函数在NewZKManager和NewRegistryCenter中各执行了一次。导致func (self *ZKManager) listenEvent() 这个函数被执行了两次。请问下是什么理由这么做？

**Comment by blackbeans** [comment]
谢谢提出这个Bug,这是在做etcd和zk时重构过程中引入的一个bug，即将在Master上修复
