### ISSUE TITLE
zk注册重连的bug，导致出现大量的无用连接

### ISSUE THREAD

**Issue by ygqwan** [blackbeans/kiteq#15]
`go-zookeeper/zk`库本身带有重连的功能，当出现`zk.StateExpired`或者`zk.StateDisconnected`后，zk库本身已经重连了，如果在`func (self *ZKManager) listenEvent()`中再次重连，会出现很多很多无用连接， 请作者看看是不是这么回事儿

**Comment by blackbeans** [comment]
收到，我确认一下

**Comment by blackbeans** [comment]
确认zk库本身已经处理了sessionexpired的事件，在registry中已经去掉了对该事件的进行重连的处理。多谢反馈
